name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
   runs-on: ubuntu-20.04
   steps:
     - name: Say manuel
       run: echo "Manuel"
     - name: list file
       run: ls