name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-20.04
   steps:
     - uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm install --no-audit --no-optional --no-fund
     - name: Linter
       run: npm run lint
     - name: Build
       run: npm run build
     - name: Tests
       run: npm run test