name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
   runs-on: ubuntu-20.04
   steps:
     - uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - uses: actions/setup-node@v2
       with:
        node_version: 14