name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  avoid-recurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm ci
     - name: Linter
       run: npm run lint
       
  build:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm ci
     - name: Build
       run: npm run build

  tests:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm ci
     - name: Tests
       run: npm run test

  test-e2e:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm ci
     - name: Test E2E
       uses: cypress-io/github-action@v2
       with: 
        command: npm run test:e2e
        start: npm run start-test
        wait-on: http://localhost:4000

  deploy:
   needs: [tests, tests-e2e]
   runs-on: ubuntu-20.04
   steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
       with:
         fetch-depth: 0
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
        node-version: 14
     - name: Intall Dependencies
       run: npm ci